packages:
  - packages/*
  - apps/*
catalogs:
  web-audio:
    "@types/audioworklet": 0.0.92
  vite:
    vite: ^7.2.6
    "vite-tsconfig-paths": ^5.1.4
  test:
    vitest: 4.0.15
  tailwindcss:
    "@tailwindcss/vite": 4.1.17
    "tailwind-merge": 3.4.0
    "tailwindcss": 4.1.17
  react-19:
    react: 19.2.1
    react-dom: 19.2.1
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3
    "@vitejs/plugin-react": 5.1.1
    babel-plugin-react-compiler: 1.0.0
ignoredBuiltDependencies:
  - "@firebase/util"
