packages:
  - packages/*
  - apps/*
catalogs:
  utils:
    "es-toolkit": 1.46.1
  node:
    "@types/node": 25.6.0
  web-audio:
    "@types/audioworklet": 0.0.99
    "node-web-audio-api": 1.0.9
  vite:
    vite: 8.0.10
    "vite-tsconfig-paths": 6.1.1
  test:
    vitest: 4.1.5
  tailwindcss:
    "@tailwindcss/vite": 4.2.4
    "tailwind-merge": 3.5.0
    "tailwindcss": 4.2.4
  react-19:
    react: 19.2.5
    react-dom: 19.2.5
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    "@vitejs/plugin-react": 6.0.1
    babel-plugin-react-compiler: 1.0.0
ignoredBuiltDependencies:
  - "@firebase/util"
