packages:
  - packages/*
  - apps/*
catalogs:
  web-audio:
    "@types/audioworklet": 0.0.92
  vite:
    vite: 7.3.1
    "vite-tsconfig-paths": 6.0.5
  test:
    vitest: 4.0.18
  tailwindcss:
    "@tailwindcss/vite": 4.1.18
    "tailwind-merge": 3.4.0
    "tailwindcss": 4.1.18
  react-19:
    react: 19.2.4
    react-dom: 19.2.4
    "@types/react": 19.2.10
    "@types/react-dom": 19.2.3
    "@vitejs/plugin-react": 5.1.2
    babel-plugin-react-compiler: 1.0.0
ignoredBuiltDependencies:
  - "@firebase/util"
