packages:
  - packages/*
  - apps/*
catalogs:
  vite:
    vite: ^7.1.9
    "vite-tsconfig-paths": ^5.1.4
  tailwindcss:
    "@tailwindcss/vite": ^4.1.14
    "tailwindcss": ^4.1.14
  react-19:
    react: 19.2.1
    react-dom: 19.2.1
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3
    "@vitejs/plugin-react": 5.1.1
    babel-plugin-react-compiler: 1.0.0
ignoredBuiltDependencies:
  - "@firebase/util"
