packages:
  - packages/*
  - apps/*
catalogs:
  vite:
    vite: ^7.1.9
    "vite-tsconfig-paths": ^5.1.4
  tailwindcss:
    "@tailwindcss/vite": ^4.1.14
    "tailwindcss": ^4.1.14
  react-19:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0
    "@vitejs/plugin-react": ^5.0.4
    babel-plugin-react-compiler: 19.1.0-rc.2
ignoredBuiltDependencies:
  - "@firebase/util"
