// Node.js version - uses node-web-audio-api polyfill
export {
  AudioContext,
  OfflineAudioContext,
  AudioBuffer,
  AudioBufferSourceNode,
  OscillatorNode,
  GainNode,
  BiquadFilterNode,
  DelayNode,
  ConvolverNode,
  DynamicsCompressorNode,
  WaveShaperNode,
  StereoPannerNode,
  AnalyserNode,
  ChannelMergerNode,
  ChannelSplitterNode,
  AudioWorkletNode,
  PeriodicWave,
  ConstantSourceNode,
  PannerNode,
  AudioListener,
  AudioParam,
  AudioDestinationNode,
} from "node-web-audio-api";
