/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatchPatchIdRouteImport } from './routes/patch.$patchId'
import { Route as InstrumentInstrumentIdRouteImport } from './routes/instrument.$instrumentId'
import { Route as InstrumentInstrumentIdPerformanceRouteImport } from './routes/instrument.$instrumentId.performance'
import { Route as InstrumentInstrumentIdDebugRouteImport } from './routes/instrument.$instrumentId.debug'

const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchPatchIdRoute = PatchPatchIdRouteImport.update({
  id: '/patch/$patchId',
  path: '/patch/$patchId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentInstrumentIdRoute = InstrumentInstrumentIdRouteImport.update({
  id: '/instrument/$instrumentId',
  path: '/instrument/$instrumentId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentInstrumentIdPerformanceRoute =
  InstrumentInstrumentIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => InstrumentInstrumentIdRoute,
  } as any)
const InstrumentInstrumentIdDebugRoute =
  InstrumentInstrumentIdDebugRouteImport.update({
    id: '/debug',
    path: '/debug',
    getParentRoute: () => InstrumentInstrumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/instruments': typeof InstrumentsRoute
  '/instrument/$instrumentId': typeof InstrumentInstrumentIdRouteWithChildren
  '/patch/$patchId': typeof PatchPatchIdRoute
  '/instrument/$instrumentId/debug': typeof InstrumentInstrumentIdDebugRoute
  '/instrument/$instrumentId/performance': typeof InstrumentInstrumentIdPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/instruments': typeof InstrumentsRoute
  '/instrument/$instrumentId': typeof InstrumentInstrumentIdRouteWithChildren
  '/patch/$patchId': typeof PatchPatchIdRoute
  '/instrument/$instrumentId/debug': typeof InstrumentInstrumentIdDebugRoute
  '/instrument/$instrumentId/performance': typeof InstrumentInstrumentIdPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/instruments': typeof InstrumentsRoute
  '/instrument/$instrumentId': typeof InstrumentInstrumentIdRouteWithChildren
  '/patch/$patchId': typeof PatchPatchIdRoute
  '/instrument/$instrumentId/debug': typeof InstrumentInstrumentIdDebugRoute
  '/instrument/$instrumentId/performance': typeof InstrumentInstrumentIdPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/instruments'
    | '/instrument/$instrumentId'
    | '/patch/$patchId'
    | '/instrument/$instrumentId/debug'
    | '/instrument/$instrumentId/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/instruments'
    | '/instrument/$instrumentId'
    | '/patch/$patchId'
    | '/instrument/$instrumentId/debug'
    | '/instrument/$instrumentId/performance'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/instruments'
    | '/instrument/$instrumentId'
    | '/patch/$patchId'
    | '/instrument/$instrumentId/debug'
    | '/instrument/$instrumentId/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  InstrumentsRoute: typeof InstrumentsRoute
  InstrumentInstrumentIdRoute: typeof InstrumentInstrumentIdRouteWithChildren
  PatchPatchIdRoute: typeof PatchPatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch/$patchId': {
      id: '/patch/$patchId'
      path: '/patch/$patchId'
      fullPath: '/patch/$patchId'
      preLoaderRoute: typeof PatchPatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument/$instrumentId': {
      id: '/instrument/$instrumentId'
      path: '/instrument/$instrumentId'
      fullPath: '/instrument/$instrumentId'
      preLoaderRoute: typeof InstrumentInstrumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument/$instrumentId/performance': {
      id: '/instrument/$instrumentId/performance'
      path: '/performance'
      fullPath: '/instrument/$instrumentId/performance'
      preLoaderRoute: typeof InstrumentInstrumentIdPerformanceRouteImport
      parentRoute: typeof InstrumentInstrumentIdRoute
    }
    '/instrument/$instrumentId/debug': {
      id: '/instrument/$instrumentId/debug'
      path: '/debug'
      fullPath: '/instrument/$instrumentId/debug'
      preLoaderRoute: typeof InstrumentInstrumentIdDebugRouteImport
      parentRoute: typeof InstrumentInstrumentIdRoute
    }
  }
}

interface InstrumentInstrumentIdRouteChildren {
  InstrumentInstrumentIdDebugRoute: typeof InstrumentInstrumentIdDebugRoute
  InstrumentInstrumentIdPerformanceRoute: typeof InstrumentInstrumentIdPerformanceRoute
}

const InstrumentInstrumentIdRouteChildren: InstrumentInstrumentIdRouteChildren =
  {
    InstrumentInstrumentIdDebugRoute: InstrumentInstrumentIdDebugRoute,
    InstrumentInstrumentIdPerformanceRoute:
      InstrumentInstrumentIdPerformanceRoute,
  }

const InstrumentInstrumentIdRouteWithChildren =
  InstrumentInstrumentIdRoute._addFileChildren(
    InstrumentInstrumentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  InstrumentsRoute: InstrumentsRoute,
  InstrumentInstrumentIdRoute: InstrumentInstrumentIdRouteWithChildren,
  PatchPatchIdRoute: PatchPatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
